require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShippingDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # ShippingDetail. As you add validations to ShippingDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "full_address_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShippingDetailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shipping_details as @shipping_details" do
      shipping_detail = ShippingDetail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shipping_details).should eq([shipping_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested shipping_detail as @shipping_detail" do
      shipping_detail = ShippingDetail.create! valid_attributes
      get :show, {:id => shipping_detail.to_param}, valid_session
      assigns(:shipping_detail).should eq(shipping_detail)
    end
  end

  describe "GET new" do
    it "assigns a new shipping_detail as @shipping_detail" do
      get :new, {}, valid_session
      assigns(:shipping_detail).should be_a_new(ShippingDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested shipping_detail as @shipping_detail" do
      shipping_detail = ShippingDetail.create! valid_attributes
      get :edit, {:id => shipping_detail.to_param}, valid_session
      assigns(:shipping_detail).should eq(shipping_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShippingDetail" do
        expect {
          post :create, {:shipping_detail => valid_attributes}, valid_session
        }.to change(ShippingDetail, :count).by(1)
      end

      it "assigns a newly created shipping_detail as @shipping_detail" do
        post :create, {:shipping_detail => valid_attributes}, valid_session
        assigns(:shipping_detail).should be_a(ShippingDetail)
        assigns(:shipping_detail).should be_persisted
      end

      it "redirects to the created shipping_detail" do
        post :create, {:shipping_detail => valid_attributes}, valid_session
        response.should redirect_to(ShippingDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shipping_detail as @shipping_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingDetail.any_instance.stub(:save).and_return(false)
        post :create, {:shipping_detail => { "full_address_name" => "invalid value" }}, valid_session
        assigns(:shipping_detail).should be_a_new(ShippingDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingDetail.any_instance.stub(:save).and_return(false)
        post :create, {:shipping_detail => { "full_address_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shipping_detail" do
        shipping_detail = ShippingDetail.create! valid_attributes
        # Assuming there are no other shipping_details in the database, this
        # specifies that the ShippingDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShippingDetail.any_instance.should_receive(:update).with({ "full_address_name" => "MyString" })
        put :update, {:id => shipping_detail.to_param, :shipping_detail => { "full_address_name" => "MyString" }}, valid_session
      end

      it "assigns the requested shipping_detail as @shipping_detail" do
        shipping_detail = ShippingDetail.create! valid_attributes
        put :update, {:id => shipping_detail.to_param, :shipping_detail => valid_attributes}, valid_session
        assigns(:shipping_detail).should eq(shipping_detail)
      end

      it "redirects to the shipping_detail" do
        shipping_detail = ShippingDetail.create! valid_attributes
        put :update, {:id => shipping_detail.to_param, :shipping_detail => valid_attributes}, valid_session
        response.should redirect_to(shipping_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the shipping_detail as @shipping_detail" do
        shipping_detail = ShippingDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipping_detail.to_param, :shipping_detail => { "full_address_name" => "invalid value" }}, valid_session
        assigns(:shipping_detail).should eq(shipping_detail)
      end

      it "re-renders the 'edit' template" do
        shipping_detail = ShippingDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipping_detail.to_param, :shipping_detail => { "full_address_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shipping_detail" do
      shipping_detail = ShippingDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => shipping_detail.to_param}, valid_session
      }.to change(ShippingDetail, :count).by(-1)
    end

    it "redirects to the shipping_details list" do
      shipping_detail = ShippingDetail.create! valid_attributes
      delete :destroy, {:id => shipping_detail.to_param}, valid_session
      response.should redirect_to(shipping_details_url)
    end
  end

end
